services:
  postgres-main:
    image: postgres:15
    container_name: postgres-main
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgresdb
      PGDATA: /data
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data 
    ports:
      - "5000:5432"
    networks:
      - postgres-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: scc0243@gmail.com
      PGADMIN_DEFAULT_PASSWORD: scc0243-2025
    ports:
      - "5050:80"
    networks:
      - postgres-network
    restart: always

networks:
  postgres-network:
